<?php
include('slider.php');
include('block_one.php');
include('block_two.php');
include('block_three.php');
include('block_five.php');
include('block_six.php');
include('block_eight.php');
include('block_night.php');
include('block_ten.php');
?>